### ISSUE TITLE
graphql-ruby 1.10.0 update breaks the gem

### ISSUE THREAD

**Issue by recurser** [DmitryTsepelev/graphql-ruby-persisted_queries#12]
Looks like a similar issue to [graphql-guard#36](https://github.com/exAspArk/graphql-guard/issues/36) and [graphql-batch#116](https://github.com/Shopify/graphql-batch/pull/116):

```
NoMethodError:
  undefined method `target' for SomeSchema:Class
# ./.bundle/gems/graphql-persisted_queries-0.1.1/lib/graphql/persisted_queries.rb:11:in `use'
# ./.bundle/gems/graphql-1.10.0/lib/graphql/schema.rb:861:in `use'
# ./app/graphql/some_schema.rb:14:in `<class:SomeSchema>'
# ./app/graphql/some_schema.rb:3:in `<top (required)>'
```

**Comment by DmitryTsepelev** [comment]
Hi @recurser, thanks for the report and for the example PRs, the fix was extremely easy 🙂I've released `0.1.2`, please let me know if it fixes the error on your side
