### ISSUE TITLE
Try cache GraphQL::Query instead of query strings

### ISSUE THREAD

**Issue by DmitryTsepelev** [DmitryTsepelev/graphql-ruby-persisted_queries#2]

**Comment by bmorton** [comment]
As I stated in #16, I’d love to take a swing at this.  I was thinking about moving the current Resolver to be a QueryStringResolver and then to implement a ParsedQueryResolver and allow that to be configured via GraphQL::PersistedQueries.use. What do you think about that?

**Comment by DmitryTsepelev** [comment]
Yeah, passing a kwarg to the `use` call (like `use GraphQL::PersistedQueries, cache_parsed_queries: true`) sounds perfect!

**Comment by DmitryTsepelev** [comment]
Closed via #39
