### ISSUE TITLE
Support multiplex

### ISSUE THREAD

**Issue by JanStevens** [DmitryTsepelev/graphql-ruby-persisted_queries#21]
Hello,

Trying to use this gem with multiplex queries but hitting some issues. Originally I posted this on graphql Ruby but it should be here

https://github.com/rmosolgo/graphql-ruby/issues/2751

Regards

**Comment by DmitryTsepelev** [comment]
Hi @JanStevens, thanks for the report! I guess the problem is that I haven't patched multiplex to support APQ, will try to fix it during the next few days

**Comment by DmitryTsepelev** [comment]
Hi @JanStevens, I've made an attempt [here](https://github.com/DmitryTsepelev/graphql-ruby-persisted_queries/pull/24), looks like tests are passing (I'm going to add some more and write docs), I'd be very grateful if you could try it out in your project and make sure it works fine.

By the way, I have a question on BatchLink usage: how are you handling a security problem with too huge queries, which is usually solved by `max_complexity`/`max_depth` ?

**Comment by JanStevens** [comment]
Thanks, ill try it out and leave comments on the MR.

For your other question, it works out of the box? I just use the provided MaxQueryComplexity and MaxQueryDepth, if one of the queries hits that limit all of them are rejected but each individual query is check against it.

Reading up on (Multiplex)[https://graphql-ruby.org/queries/multiplex.html] it is clearly stated that:
> NOTE: As an implementation detail, all queries are run inside multiplexes. That is, a stand-alone query is executed as a “multiplex of one”, so instrumentation and multiplex analyzers and instrumentation will apply to standalone queries run with MySchema.execute(...).

So I'm wondering if it makes more sense to use the context for persisted queries instead of patching `extensions` in it? Or is `extensions` part of the spec and we could ask graphql-ruby to support it?

**Comment by DmitryTsepelev** [comment]
> For your other question, it works out of the box?
Yep, I realized that complexity analysis could be run for each query in the batch, so it's safe.

> So I'm wondering if it makes more sense to use the context for persisted queries instead of patching extensions in it?

Extensions is not a part of the spec (to be precise, HTTP is not part of the spec, GraphQL is transport–agnostic 🤓), but [apollo-link-persisted-queries passes](https://github.com/apollographql/apollo-link-persisted-queries/blob/master/src/index.ts#L120) extensions as an HTTP parameter, so we have to patch `graphql-ruby` to _know_ about this parameter (maybe we should add the ability to accept _any_ parameters to `execute`/`multiplex` on the `graphql-ruby` level?)

**Comment by JanStevens** [comment]
Or we could shove the extensions param inside the context? That would involve less patching and more following regular extension flow

**Comment by DmitryTsepelev** [comment]
I'll need to try it out (made #25 to not forget about it), let's finalize multiplex and then I'll give it a shot

**Comment by DmitryTsepelev** [comment]
Rolled out a new version! Closing the issue
