### ISSUE TITLE
Squish queries

### ISSUE THREAD

**Issue by JanStevens** [DmitryTsepelev/graphql-ruby-persisted_queries#27]
Hello,

I was thinking of adding `squish` when storing queries. There is no point in saving line brakes or spaces.

Downside is that there is of course a difference in the hash (not sure if that is a problem or not)

Squish from rails could be implemented as
```ruby
def squish(query)
  query.gsub(/[[:space:]]+/, " ").strip
end

**Comment by DmitryTsepelev** [comment]
I don't mind having it as a configurable option — if queries are big enough it might reduce the memory size to store them

**Comment by JanStevens** [comment]
Yea I don't think it's a great idea anymore. It might save space but it also messes up the hash integrity.

When things go wrong there is no way to calculate the right hash again that was send from the client if you only got your server side cache.
