### ISSUE TITLE
Support for snake_case

### ISSUE THREAD

**Issue by RynoPi** [DmitryTsepelev/graphql-ruby-persisted_queries#38]
Looking at the code, we can see that the library traverses the code in camel-case such as the function below:
`
def hash
    @hash ||= @extensions.dig("persistedQuery", "sha256Hash")
end
`
Is it possible for you to add functionality to also handle the case where the extensions object is passed through as snake_case?

**Comment by DmitryTsepelev** [comment]
Hi @RynoPi!

The gem was designed to work with Apollo Persisted Queries link, which [sends](https://github.com/apollographql/apollo-client/blob/main/src/link/persisted-queries/index.ts#L242) these params in camel–case, and looks like there is no way to change this behavior on their side. Where these snake–case params came from in your case?

**Comment by RynoPi** [comment]
Hi @DmitryTsepelev.

Thanks for the quick reply. We have a middle-ware that is setup to convert all request data to snake-case (maybe not conventional ruby). Currently we have implemented a 'hacky' way of converting the extensions params to be camel-case for the library. We feel like it might be better to have functionality in this gem to switch between the two modes.

I do realize that this seems more like a nice to have and could be a lengthy process, but wanted to bring it to your attention.

**Comment by DmitryTsepelev** [comment]
It would be really nice if you could post your patch here, it might help someone in future 🙂

**Comment by RynoPi** [comment]
No problem. Please note that I do not have much experience in ruby so if you see any way to improve let me know.

Here is the function:
```
    def create_extensions_hash(params)
        return params[:extensions] unless params[:extensions].present?
        return params[:extensions] unless params[:extensions][:persisted_query].present?
        extensions = {
            'persistedQuery' => {
            'sha256Hash' => params[:extensions][:persisted_query][:sha256_hash],
            'version' => params[:extensions][:persisted_query][:version]
            }
        }

        extensions
    end

```
We implemented it as a mixin. And then we pass this functions to the extensions part of GraphQL#execute.

**Comment by DmitryTsepelev** [comment]
I guess you could patch [this](https://github.com/DmitryTsepelev/graphql-ruby-persisted_queries/blob/master/lib/graphql/persisted_queries/resolver.rb#L53) method, something like (I haven't checked it):

```ruby
# somewhere in initializer
GraphQL::PersistedQueries::Resolver.prepend(
  Module.new do
    def hash
      @hash ||= @extensions.dig("persisted_query", "sha256_hash")
    end
  end
)
```
