### ISSUE TITLE
Error in redis_with_local_cache

### ISSUE THREAD

**Issue by raffij** [DmitryTsepelev/graphql-ruby-persisted_queries#46]
```
class WebSchema < GraphQL::Schema
  mutation(Types::MutationType)
  query(Types::QueryType)

  use GraphQL::PersistedQueries,
      store: :redis_with_local_cache,
      redis_client: { redis_url: Rails.application.config.x.redis.url },
      expiration: 2_592_000, # 30 days
      compiled_queries: true
end
```
	 8: from /vendor/bundle/ruby/2.5.0/gems/graphql-1.12.8/lib/graphql/schema.rb:935:in `use'
	 7: from /vendor/bundle/ruby/2.5.0/gems/graphql-persisted_queries-1.2.1/lib/graphql/persisted_queries.rb:36:in `use'
	 6: from /vendor/bundle/ruby/2.5.0/gems/graphql-persisted_queries-1.2.1/lib/graphql/persisted_queries/schema_patch.rb:33:in `configure_persisted_query_store'
	 5: from /vendor/bundle/ruby/2.5.0/gems/graphql-persisted_queries-1.2.1/lib/graphql/persisted_queries/store_adapters.rb:17:in `build'
	 4: from /vendor/bundle/ruby/2.5.0/gems/graphql-persisted_queries-1.2.1/lib/graphql/persisted_queries/store_adapters.rb:22:in `build_by_name'
	 3: from /vendor/bundle/ruby/2.5.0/gems/graphql-persisted_queries-1.2.1/lib/graphql/persisted_queries/store_adapters.rb:22:in `new'
	 2: from /vendor/bundle/ruby/2.5.0/gems/graphql-persisted_queries-1.2.1/lib/graphql/persisted_queries/store_adapters/redis_with_local_cache_store_adapter.rb:21:in `initialize'
	 1: from /vendor/bundle/ruby/2.5.0/gems/graphql-persisted_queries-1.2.1/lib/graphql/persisted_queries/store_adapters/redis_with_local_cache_store_adapter.rb:21:in `new'
/vendor/bundle/ruby/2.5.0/gems/graphql-persisted_queries-1.2.1/lib/graphql/persisted_queries/store_adapters/memory_store_adapter.rb:8:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

**Comment by DmitryTsepelev** [comment]
Fixed, thanks!
