### ISSUE TITLE
Skip the redis_client argument when ENV["REDIS_URL"] is defined.

### ISSUE THREAD

**Issue by louim** [DmitryTsepelev/graphql-ruby-persisted_queries#48]
Hey!

it is possible to completely skip the `redis_client` argument when `ENV["REDIS_URL"]` is defined?

What I tried:
```ruby
use GraphQL::PersistedQueries,
      compiled_queries: true,
      store: :redis
```

but it raises an error:
```
missing keyword: redis_client
/Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/graphql-persisted_queries-1.2.2/lib/graphql/persisted_queries/store_adapters/redis_with_local_cache_store_adapter.rb:11:in `initialize'
/Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/graphql-persisted_queries-1.2.2/lib/graphql/persisted_queries/store_adapters.rb:22:in `new'
/Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/graphql-persisted_queries-1.2.2/lib/graphql/persisted_queries/store_adapters.rb:22:in `build_by_name'
/Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/graphql-persisted_queries-1.2.2/lib/graphql/persisted_queries/store_adapters.rb:17:in `build'
/Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/graphql-persisted_queries-1.2.2/lib/graphql/persisted_queries/schema_patch.rb:33:in `configure_persisted_query_store'
/Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/graphql-persisted_queries-1.2.2/lib/graphql/persisted_queries.rb:36:in `use'
/Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/graphql-1.12.8/lib/graphql/schema.rb:935:in `use'
```
I ended up using an empty hash. but it feels a bit weird. Would it be possible to completely skip the `redis_client`?
```ruby
  use GraphQL::PersistedQueries,
      compiled_queries: true,
      store: :redis,
      redis_client: {}
```

**Comment by DmitryTsepelev** [comment]
Hi @louim!

Thank you for reporting that, sounds like a bug. Looks like we need to change the code a bit:

1. https://github.com/DmitryTsepelev/graphql-ruby-persisted_queries/blob/32ae7622cf1fbc49ebae1ae3885e39c7ae80a260/lib/graphql/persisted_queries/store_adapters/redis_store_adapter.rb#L13 to allow `nil` in `redis_client`
2. https://github.com/DmitryTsepelev/graphql-ruby-persisted_queries/blob/32ae7622cf1fbc49ebae1ae3885e39c7ae80a260/lib/graphql/persisted_queries/store_adapters/redis_store_adapter.rb#L40 — add `|| redis_client.nil?`
3. change specs

Do you want to try to make a PR? 🙂
