### ISSUE TITLE
Adding some additional metadata in cache-store along with the query itself and its hash.

### ISSUE THREAD

**Issue by yildizsc** [DmitryTsepelev/graphql-ruby-persisted_queries#66]
Hey @DmitryTsepelev , thank you very much for this great gem. We would like to use this gem in our project but I have a quick question. We have a rate limiter depending on GraphQL query's complexity. For instance, we are doing static analysis to measure the cost of the query before executing it via resolvers. Disabling the analysis, or caching the query won't help us here. I wish there was an API that helps to save some metadata to memory or any cache store along with the query or its hash. What I mean here is that saving some metadata is saving the cost, complexity, and the query with a simple json or hash data structure on Redis side so that when client hits the server with the hash I can retrieve the cached cost or the metadata from the cache-store. 

If this gem does not cover our needs, I would like to implement it and send a pull request.  Your guidance is welcome since I am not familiar with API. 

Thank you again for the great work.

**Comment by DmitryTsepelev** [comment]
Hey! Sounds like you can use tracing [API](https://github.com/DmitryTsepelev/graphql-ruby-persisted_queries/blob/master/docs/tracing.md): when query is [persisted](https://github.com/DmitryTsepelev/graphql-ruby-persisted_queries/blob/master/lib/graphql/persisted_queries/store_adapters/base_store_adapter.rb#L27) we fire "save_query" event.

We can define our own tracer:

```ruby
class ComplecityPersistedQueryTracer
  def self.trace(key, data)
    yield.tap do |result|
      when "persisted_queries.save_query"
        # grab complexity from the context/Thread.current and save it whereever you want
      end
    end
  end
end
```

Plug it into schema, find out a way to access complexity from tracer and save it.

Please let me know if it works 🙂

**Comment by yildizsc** [comment]
Hi @DmitryTsepelev , I have installed this gem and tried it. I dug deeper and noticed that all analyzers are working even though caching the AST. This is working with our setup now. I have proofed it with a bunch of rspec tests. 

Thank you very much for fast response and for this great gem.
