### ISSUE TITLE
Undefined method `using_ast_analysis?' for class 

### ISSUE THREAD

**Issue by celsoMartins** [DmitryTsepelev/graphql-ruby-persisted_queries#80]
Hi there!

After the last update, we started to get the exception below.

The stacktrace shows an issue in the persisted-queries module.

Thanks in advance.

```
bundle list|grep graphql                                                                                                                                          [20:02:14]
  * graphql (2.3.14)
  * graphql-batch (0.6.0)
  * graphql-persisted_queries (1.8.1)
  * graphql_devise (1.5.0)
  * rubocop-graphql (1.5.4)
```

```
     NoMethodError:
       undefined method `using_ast_analysis?' for class OurSchemaClass
     # gems/graphql-persisted_queries-1.8.1/lib/graphql/persisted_queries/schema_patch.rb:101:in `prepare_analyzer'
     # gems/graphql-persisted_queries-1.8.1/lib/graphql/persisted_queries/schema_patch.rb:81:in `verify_http_method='
     # gems/graphql-persisted_queries-1.8.1/lib/graphql/persisted_queries.rb:28:in `use'
     # gems/graphql-2.3.11/lib/graphql/schema.rb:327:in `use'
```

**Comment by celsoMartins** [comment]
I changed my gem source to use the master branch and the problem was solved.

`gem 'graphql-persisted_queries', git: 'https://github.com/DmitryTsepelev/graphql-ruby-persisted_queries.git', branch: 'master'`

Looking forward to getting the package update.

**Comment by DmitryTsepelev** [comment]
Hi! Correct, it's in the master for now, I usually make one release per month :)

**Comment by celsoMartins** [comment]
I smell a Scrum team.

See the light. Meet Kanban and the continuous flow. =)

Just kidding.

Thanks for the confirmation.
